version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testing

  api:
    build: ./api
    container_name: api
    depends_on:
      - database
    ports:
      - 5000:80
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:80

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
    ports:
      - 80:80
