version: '3'
services:
  api:
    build: ./api
    container_name: api
    ports:
      - 8000:80
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:80

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - api
      - frontend
    links:
      - api
      - frontend
    ports:
      - 80:80