version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testing

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api_dev
    depends_on:
      - database
    ports:
      - 5000:80
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_dev
    ports:
      - 3000:80
